name: Compile LaTeX Thesis

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build_pdf:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: thesis 
          root_file: main.tex 
          latexmk_use_xelatex: true 

      - name: Upload PDF as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Thesis-PDF
          path: thesis/main.pdf